runtime: nodejs20
service: note-fe-059

handlers:
  # Menangani folder root agar langsung membuka index.html
  - url: /
    static_files: index.html
    upload: index.html

  # Menangani semua file statis lainnya (.css, .js, gambar)
  - url: /(.*)
    static_files: \1
    upload: (.*)